models/question.py
from models.mongo import Mongo

class Question(Mongo):
    __fields__ = Mongo.__fields__ + [
        ('title', str, ''),
        ('content', str, ''),
        ('uid', int, 0),
        ('user', dict, {}),
        ('follows', dict, {}),
    ]

    def answers(self):
        from .answer import Answer
        ans = Answer.find_all(qid=self.id)
        return ans

routes/answer.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)
import uuid
from routes import *
from utils import log
import json

from models.question import Question
from models.answer import Answer

main = Blueprint('answer', __name__)

# 防csrf
csrf_tokens = dict()

@main.route("/")
def index():
    qid = int(request.args.get('qid'))
    # log('index qid=', qid)
    u = current_user()
    if u is None:
        return redirect(url_for('user.login'))
    qu = Question.get(qid)
    an = Answer.find_all(qid=qid)
    return render_template("answer/index.html", qu=qu, an=an)

@main.route("/add", methods=["POST"])
def add():   
    form = request.form
    qid = form['qid']
    # log('add qid=', qid)
    u = current_user()
    if u is None:
        return redirect(url_for('user.login'))
    r = Answer.new(form, uid=u.id, user=u.__dict__)
    return redirect(url_for('question.detail', id=qid))

@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 question 用户是', u, id)
            Question.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)

@main.route("/like")
def like():
    id = int(request.args.get('id'))
    an = Answer.find(id)
    an.like = an.like + 1
    an.save()
    return redirect(url_for('question.detail', id=an.qid))

@main.route("/unlike")
def unlike():
    id = int(request.args.get('id'))
    an = Answer.find(id)
    an.unlike = an.unlike + 1
    an.save()
    return redirect(url_for('question.detail', id=an.qid))

routes/question.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)
import uuid
from routes import *

from models.question import Question
from models.answer import Answer
from utils import log

main = Blueprint('question', __name__)

# 防csrf
csrf_tokens = dict()

@main.route("/")
def index():
    token = str(uuid.uuid4())
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    csrf_tokens[token] = user.id
    qu = Question.all()
    return render_template("question/index.html", qu=qu,  token=token, user=user)


@main.route("/add", methods=['GET', 'POST'])
def add():
    if request.method == 'GET':
        return render_template('question/add.html')
    else:   
        form = request.form
        u = current_user()
        if u is None:
            return redirect(url_for('user.login'))
        
        m = Question.new(form, uid=u.id, user=u.__dict__)
        return redirect(url_for('.index'))

@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 question 用户是', u, id)
            Question.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)

@main.route('/detail/<int:id>')
def detail(id):
    qu = Question.get(id)
    an = Answer.find_all(qid=id)
    u = current_user()
    follows = qu.follows
    log('detail follows', follows)
    log('detail u', u)
    if str(u.id) in follows:
        is_follow = True
    else:
        is_follow = False

    return render_template("question/detail.html", question=qu, answer=an, is_follow=is_follow)


@main.route("/follow")
def follow():
    id = int(request.args.get('id'))
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find(id)
    follows = qu.follows
    log('follow1', follows)
    if not follows:
        follows = {}
    follows[str(user.id)] = user.__dict__
    log('follow2', follows)
    qu.follows = follows
    log('follow3',qu.follows)
    qu.save()
    return redirect(url_for('question.detail', id=id))

@main.route("/unfollow")
def unfollow():
    id = int(request.args.get('id'))
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find(id)
    follows = qu.follows
    log('unfollow1', follows)
    del follows[str(user.id)]
    # follows = follows.pop(str(user.id))
    log('unfollow2', follows)
    qu.follows = follows
    log('unfollow3',qu.follows)
    qu.save()
    return redirect(url_for('question.detail', id=id))

templates/question/add.html
{% extends "base.html" %}

{% block title %} 提问 {% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}

    <div class="container">
        <form method="post" action="{{ url_for('question.add') }}">
            <div class="form-group">
                <label for="username">标题</label>
                <input type="text" class="form-control input-xlarge" id="title" name="title">
            </div>
            <div class="form-group">
                <label for="content">内容</label>
                <textarea class="form-control" id="content" name="content"></textarea>
            </div>
    
            <div class="checkbox">
                <label>
                    <p>{{ msg }}</p>
                </label>
            </div>
            <button type="submit" class="btn btn-default">提交</button>
        </form>
    </div>

{% endblock %}

templates/question/detail.html
{% extends "base.html" %}

{% block title %} 问题 {% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="/static/bootstrap-markdown/css/bootstrap-markdown.min.css" type="text/css">
    <script type="text/javascript" src="/static/bootstrap-markdown/js/bootstrap-markdown.js" ></script>
    <script type="text/javascript" src="/static/bootstrap-markdown/locale/bootstrap-markdown.zh.js" ></script> 
{% endblock %}

{% block content %}
    <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-9">
                            <span class="glyphicon glyphicon-list-alt"></span> 最新动态
                        </div>
                    </div>
                    <hr>

                        <div class="row">
							<div class="col-md-12" id="question">
								<p>{{ question.title }}</p>
								<p>{{ question.content }}</p>
								<ul class="list-inline">
                                    {% if is_follow %}
                                        <li><span class="glyphicon glyphicon-plus"></span> 已关注</li>
                                        <li><a href="{{ url_for('question.unfollow', id=question.id) }}"><span class="glyphicon glyphicon-minus"></span> 取消关注</a></li>                                        
                                    {% else %}
                                        <li><a href="{{ url_for('question.follow', id=question.id) }}"><span class="glyphicon glyphicon-plus"></span> 关注问题</a></li>                                        
                                    {% endif %}
                                </ul>
							</div>
						</div>
                        <hr>

                        {% for vo in answer %}
                            <div class="row">
                                <div class="col-md-12" id="answer">
                                    <p data-provide="markdown">{{ vo.content }}</p>
                                    <ul class="list-inline">
                                        <li><a href="{{ url_for('answer.like', id=vo.id) }}"><span class="glyphicon glyphicon-thumbs-up"></span> 赞成 {{ vo.like }}</a></li>
                                        <li><a href="{{ url_for('answer.unlike', id=vo.id) }}"><span class="glyphicon glyphicon-thumbs-down"></span> 反对 {{ vo.unlike }}</a></li>
                                    </ul>
                                </div>
                            </div>
                            <hr>
                        {% endfor %}
                        <div class="row">
                            <div class="col-md-12" id="answer">
                                <form method="post" action="{{ url_for('answer.add') }}">
                                    <input type="hidden" name="qid" value="{{ question.id }}">
                                    <div class="form-group">
                                        <label for="content">回答</label>
                                        <textarea id="id-content-edit" class="form-control" id="content" name="content"  rows="10"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-default">提交</button>
                                </form>
                                <P>{{ msg }}</P>
                            </div>
                        </div>            
                </div>
				
            <div class="col-md-4">
                <div class="row">

                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $("#id-content-edit").markdown({autofocus:false, savable:false, language:'zh'})   
        })
    </script>

{% endblock %}

templates/question/index.html
{% extends "base.html" %}

{% block title %} 问题列表 {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-9">
                        <span class="glyphicon glyphicon-list-alt"></span> 问题列表
                    </div>
                    <div class="col-md-3 text-right">
                        <span class="glyphicon glyphicon-cog"></span> 设置
                    </div>
                </div>
                <hr>

                {% for vo in qu %}
                    <div class="row">
                        <div class="col-md-12" id="question">
                            <p><a href="{{ url_for('question.detail', id=vo.id) }}">{{ vo.title }}</a></p>
                            <p>{{ vo.content }}</p>
                            <ul class="list-inline">
                                <li><a href="{{ url_for('question.detail', id=vo.id) }}"><span class="glyphicon glyphicon-comment"></span> 回答问题 </a></li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                {% endfor %}

            </div>
				
            <div class="col-md-4">
                <div class="row">

                </div>
            </div>
        </div>
    </div>

{% endblock %}