routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
)
import re
from routes import *
from utils import log
from config import user_img_director
from models.answer import Answer
from models.question import Question

main = Blueprint('index', __name__)


@main.route("/")
def index():
    user = current_user()
    answer = Answer.find_all()
    question = Question.find_all()
    
    # log('answer', answer)
    # log('question', question)   
    list_data = sorted(answer + question, key = lambda i:int(i.created_time), reverse = True)
    return render_template("index.html", user=user, list_data=list_data, Answer=Answer)

@main.route("/uploads/img/<filename>")
def uploads(filename):
    return send_from_directory(user_img_director, filename)

@main.route("/search")
def search():
    keyword = request.args.get('keyword')
    # qu = Question.find_all(title=keyword)    
    qu = Question.find_all(title=re.compile(keyword))
    # log(keyword)
    # log(qu)
    return render_template("search.html", qu=qu, keyword=keyword)

routes/question.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)
import uuid
from routes import *

from models.question import Question
from models.answer import Answer
from utils import log

main = Blueprint('question', __name__)

# 防csrf
csrf_tokens = dict()

@main.route("/")
def index():
    token = str(uuid.uuid4())
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    csrf_tokens[token] = user.id
    qu = Question.all()
    return render_template("question/index.html", qu=qu,  token=token, user=user)


@main.route("/add", methods=['GET', 'POST'])
def add():
    if request.method == 'GET':
        return render_template('question/add.html')
    else:   
        form = request.form
        u = current_user()
        if u is None:
            return redirect(url_for('user.login'))
        
        m = Question.new(form, uid=u.id, user=u.__dict__)
        return redirect(url_for('.index'))

@main.route("/delete")
def delete():
    id = int(request.args.get('id'))
    token = request.args.get('token')
    u = current_user()
    # 判断 token 是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        if u is not None:
            print('删除 question 用户是', u, id)
            Question.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        abort(403)

@main.route('/detail/<int:id>')
def detail(id):
    qu = Question.get(id)
    an = Answer.find_all(qid=id)
    u = current_user()
    follows = qu.follows
    log('detail follows', follows)
    log('detail u', u)
    if str(u.id) in follows:
        is_follow = True
    else:
        is_follow = False

    return render_template("question/detail.html", question=qu, answer=an, is_follow=is_follow)


@main.route("/follow")
def follow():
    id = int(request.args.get('id'))
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find(id)
    follows = qu.follows
    log('follow1', follows)
    if not follows:
        follows = {}
    follows[str(user.id)] = user.__dict__
    log('follow2', follows)
    qu.follows = follows
    log('follow3',qu.follows)
    qu.save()
    return redirect(url_for('question.detail', id=id))

@main.route("/unfollow")
def unfollow():
    id = int(request.args.get('id'))
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find(id)
    follows = qu.follows
    log('unfollow1', follows)
    del follows[str(user.id)]
    # follows = follows.pop(str(user.id))
    log('unfollow2', follows)
    qu.follows = follows
    log('unfollow3',qu.follows)
    qu.save()
    return redirect(url_for('question.detail', id=id))

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    flash,
)

import os
from werkzeug.utils import secure_filename
from models.user import User
from utils import log
from config import user_img_director
from models.answer import Answer
from models.question import Question

main = Blueprint('user', __name__)

def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


@main.route("/")
def index():
    return redirect(url_for('.login'))

@main.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('user/register.html')
    else:     
        form = request.form
        # 用类函数来判断
        u = User.register(form)
        # log('register', u)
        if u['status'] is False:
            msg = u['msg'] 
            return render_template('user/register.html', msg=msg)
        else:
            return redirect(url_for('.login'))

@main.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:       
        form = request.form
        log('login', form)
        u = User.validate_login(form)
        if u['status'] is False:
            msg = u['msg'] 
            return render_template('user/login.html', msg=msg)
        else:
            user = u['data']
            # session 中写入 user_id
            session['user_id'] = user.id
            # 设置 cookie 有效期为 永久
            session.permanent = True
            return redirect(url_for('index.index'))

@main.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('index.index'))


@main.route('/setting', methods=['GET', 'POST'])
def setting():
    u = current_user()
    if request.method == 'GET':    
        if u is None:
            return redirect(url_for('.login'))
        else:
            return render_template('user/setting.html', user=u)
    else:     
        form = request.form
        name = form.get('username', '')
        pwd = form.get('password', '')
        area = form.get('area', '')
        job = form.get('job', '')
        if len(name) < 2:
            return render_template('user/setting.html', msg='用户名不能少于2位', user=u)
        elif User.find_by(username=name).id != u.id:
            return render_template('user/setting.html', msg='用户名已存在', user=u)
        else:
            if 'file' in request.files:
                file = request.files['file']
                # log('file', file)
                u.avatar = add_img(file)

            u.username = name
            if pwd is not '':
                u.password = User.salted_password(pwd)
            u.area = area
            u.job = job
            u.save()
            return render_template('user/setting.html', msg='修改成功', user=u)

def allow_img(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_img_type
    return suffix in accept_user_img_type

def add_img(file):
    if file.filename == '':
        return redirect(request.url)

    if allow_img(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_img_director, filename))
        return filename
    else:
        return ''

@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_img_director, filename)

@main.route("/people")
def people():
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find_all(uid=user.id)
    an = Answer.find_all(uid=user.id)

    return render_template("user/people.html", user=user, qu=qu, an=an)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <title>{% block title %}{% endblock %} - 知否</title>
            <script src="/static/js/jquery/2.0.0/jquery.min.js"></script>
            <link href="/static/css/bootstrap/3.3.6/bootstrap.min.css" rel="stylesheet">
            <script src="/static/js/bootstrap/3.3.6/bootstrap.min.js"></script>
        {% endblock %}
    </head>
    <body>
        
        <!-- nav start -->
		<nav class="navbar navbar-default">
			<div class="container">
				<!-- brand -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a href="{{ url_for('index.index') }}" class="navbar-brand">
						知否
					</a>
				</div>
				
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<!-- search start -->
					<form class="navbar-form navbar-left" role="search" method="get" action="{{ url_for('index.search') }}" >
						<div class="form-group has-feedback">
							<div class="input-group">
								<input type="text" name="keyword" class="form-control" placeholder="搜索问题...">
								<span class="input-group-btn">
									<button class="btn btn-default" type="submit">
										<span class="glyphicon glyphicon-search"></span>
									</button>
								</span>
							</div>
                        </div>
                        <a href="{{ url_for('question.add') }}">
                            <button type="button" class="btn btn-primary" >提问</button>
                        </a>
					</form>
					<!-- search end -->
					
					<!-- main-content -->
					<ul class="nav navbar-nav">
						<li {% if request.url_rule.endpoint.split('.')[0] == 'index' %} class="active" {% endif %}><a href="{{ url_for('index.index') }}">首页</a></li>
						<li {% if request.url_rule.endpoint.split('.')[0] == 'question' %} class="active" {% endif %}><a href="{{ url_for('question.index') }}">问题</a></li>
						<!-- <li><a href="#">发现</a></li>
						<li><a href="#">消息</a></li> -->
					</ul>
					<!-- main-content end -->
					<!-- right-side -->
					<ul class="nav navbar-nav navbar-right">

						{% if current_user() %}
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
									<img src="{{ '/uploads/img/' + current_user().avatar }}" alt="" style="width: 20px; height: 20px;">
									{{ current_user().username }}
								</a>
								<ul class="dropdown-menu" role="menu">
									<li><a href="{{ url_for('user.people') }}"><span class="glyphicon glyphicon-user"></span> 我的主页</a></li>
									<!-- <li class="divider"></li>
									<li><a href="#"><span class="glyphicon glyphicon-envelope"></span> 私信</a></li> -->
									<li class="divider"></li>
									<li><a href="{{ url_for('user.setting') }}"><span class="glyphicon glyphicon-cog"></span> 设置</a></li>
									<li class="divider"></li>
									<li><a href="{{ url_for('user.logout') }}"><span class="glyphicon glyphicon-off"></span> 退出</a></li>
								</ul>
							</li>
						{% else %}
							<li class="dropdown">
								<a href="{{ url_for('user.login') }}" class="dropdown-toggle" role="button" aria-expanded="false">
									请登陆
								</a>
							</li>
						{% endif %}

					</ul>
					<!-- right-side end -->
				</div>
			</div>
		</nav>
		<!-- nav end -->

        {% block content %}{% endblock %}
       

    </body>
</html>

  

templates/index.html
{% extends "base.html" %}

{% block title %} 首页 {% endblock %}

{% block head %}
	{{  super()  }}	
{% endblock %}

{% block content %}
        <div class="container">
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-9">
							<span class="glyphicon glyphicon-list-alt"></span> 最新动态
						</div>
						<div class="col-md-3 text-right">
							<a href="{{ url_for('user.setting') }}">
								<span class="glyphicon glyphicon-cog"></span> 设置
							</a>
						</div>
					</div>
					<hr>
					
					{% for vo in list_data %}

						{% if isinstance(vo, Answer) %}
							<div class="row">
								<div class="col-md-1">
									<div class="row">
										<a href="#"><img class="img-responsive img-rounded" src="{{ '/uploads/img/' + vo.user.avatar }}" alt=""></a>
									</div>
									<div class="row">
										<a href="#"><div class="text-center number">{{ loop.index }}</div></a>
									</div>
								</div>
								<div class="col-md-11" id="question">
									<p><a href="#">{{ vo.user.username }}</a> 回答了问题 • {{ time_format(vo.created_time) }}</p>
									<p><a href="{{ url_for('question.detail', id=vo.question().id) }}"><strong>{{ vo.question().title }}</strong></a></p>
									{% if (vo.user.job and vo.user.area) %}
										<p>{{ vo.user.job }}，{{ vo.user.area }}</p>
									{% endif %}
									<p>{{ vo.content }}</p>
									<ul class="list-inline">									
										<li><a href="{{ url_for('question.detail', id=vo.question().id) }}"><span class="glyphicon glyphicon-comment"></span> 回答问题 </a></li>
										<!-- <li><a href="#"><span class="glyphicon glyphicon-heart-empty"></span> 感谢</a></li>
										<li><a href="#"><span class="glyphicon glyphicon-share"></span> 分享</a></li>
										<li><a href="#"><span class="glyphicon glyphicon-bookmark"></span> 收藏</a></li>
										<li><a href="#">• 没有帮助</a></li>
										<li><a href="#">• 举报</a></li> -->
									</ul>
								</div>
							</div>
							<hr>
						{% else %}
							<div class="row">
								<div class="col-md-1">
									<div class="row">
										<a href="#"><img class="img-responsive img-rounded" src="{{ '/uploads/img/' + vo.user.avatar }}" alt=""></a>
									</div>
									<div class="row">
										<a href="#"><div class="text-center number">{{ loop.index }}</div></a>
									</div>
								</div>
								<div class="col-md-11" id="question">
									<p><a href="#">{{ vo.user.username }}</a> 提出问题 • {{ time_format(vo.created_time) }}</p>
									<p><a href="{{ url_for('question.detail', id=vo.id) }}"><strong>{{ vo.title }}</strong></a></p>
									{% if (vo.user.job and vo.user.area) %}
										<p>{{ vo.user.job }}，{{ vo.user.area }}</p>
									{% endif %}
									<p>{{ vo.content }}</p>
									<ul class="list-inline">									
										<li><a href="{{ url_for('question.detail', id=vo.id) }}"><span class="glyphicon glyphicon-comment"></span> 回答问题 </a></li>
										<!-- <li><a href="#"><span class="glyphicon glyphicon-heart-empty"></span> 感谢</a></li>
										<li><a href="#"><span class="glyphicon glyphicon-share"></span> 分享</a></li>
										<li><a href="#"><span class="glyphicon glyphicon-bookmark"></span> 收藏</a></li>
										<li><a href="#">• 没有帮助</a></li>
										<li><a href="#">• 举报</a></li> -->
									</ul>
								</div>
							</div>
							<hr>
						{% endif %}


					{% endfor %}
					
				</div>
				
				<div class="col-md-4">
					<div class="row">
						<!-- <a href="{{ url_for('question.add') }}">提问</a> -->
					</div>
				</div>
			</div>
		</div>

{% endblock %}
  

templates/search.html
{% extends "base.html" %}

{% block title %} 搜索结果 {% endblock %}

{% block head %}
	{{  super()  }}	
{% endblock %}

{% block content %}
        <div class="container">
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-12">
							<span class="glyphicon glyphicon-list-alt"></span> “{{ keyword }}”的搜索结果
						</div>
					</div>
					<hr>
				
					{% if qu %}

						{% for vo in qu %}
							<div class="row">
								<div class="col-md-12" id="question">
									<p><a href="{{ url_for('question.detail', id=vo.id) }}">{{ vo.title }}</a></p>
									<p>{{ vo.content }}</p>
								</div>
							</div>
							<hr>
						{% endfor %}

					{% else %}
					
						<div class="row">
							<div class="col-md-12">
								<p>找不到搜索结果</p>
							</div>
						</div>

					{% endif %}
					
				</div>
				
				<div class="col-md-4">
					<div class="row">
						<!-- <a href="{{ url_for('question.add') }}">提问</a> -->
					</div>
				</div>
			</div>
		</div>

{% endblock %}
  