models/user.py
from models.mongo import Mongo
from utils import log

class User(Mongo):
    __fields__ = Mongo.__fields__ + [
        ('username', str, ''),
        ('password', str, ''),
        ('avatar', str, ''),
        ('area', str, ''),
        ('job', str, ''),
    ]

    """
        User 是一个保存用户数据的 model
        现在只有两个属性 username 和 password
        """

    def __init__(self):
        self.avatar = 'default.png'
        
    @classmethod
    def salted_password(self, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib
        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        pwd = form.get('password', '')
        if len(name) < 2:
            return {'data': None, 'msg': '用户名不能少于2位', 'status': False} 
        elif not User.find_by(username=name) is None:
            return {'data': None, 'msg': '用户名已存在', 'status': False} 
        else:
            u = User.new(form)
            u.password = u.salted_password(pwd)
            u.save()
            return {'data': u, 'msg': '注册成功', 'status': True} 

    @classmethod
    def validate_login(cls, form):
        u = User()
        u.username = form.get("username", '')
        u.password = form.get("password", "")
        user = User.find_by(username=u.username)
        log('validate_login, user',user)
        if user is None:
            return {'data': None, 'msg': '用户名不存在', 'status': False} 
        elif user.password != u.salted_password(u.password):    
            return {'data': None, 'msg': '密码不正确', 'status': False} 
        else:
            return {'data': user, 'msg': '登陆成功', 'status': True} 

routes/user.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    flash,
)

import os
from werkzeug.utils import secure_filename
from models.user import User
from utils import log
from config import user_img_director
from models.answer import Answer
from models.question import Question

main = Blueprint('user', __name__)

def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


@main.route("/")
def index():
    return redirect(url_for('.login'))

@main.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('user/register.html')
    else:     
        form = request.form
        # 用类函数来判断
        u = User.register(form)
        # log('register', u)
        if u['status'] is False:
            msg = u['msg'] 
            return render_template('user/register.html', msg=msg)
        else:
            return redirect(url_for('.login'))

@main.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:       
        form = request.form
        log('login', form)
        u = User.validate_login(form)
        if u['status'] is False:
            msg = u['msg'] 
            return render_template('user/login.html', msg=msg)
        else:
            user = u['data']
            # session 中写入 user_id
            session['user_id'] = user.id
            # 设置 cookie 有效期为 永久
            session.permanent = True
            return redirect(url_for('index.index'))

@main.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('index.index'))


@main.route('/setting', methods=['GET', 'POST'])
def setting():
    u = current_user()
    if request.method == 'GET':    
        if u is None:
            return redirect(url_for('.login'))
        else:
            return render_template('user/setting.html', user=u)
    else:     
        form = request.form
        name = form.get('username', '')
        pwd = form.get('password', '')
        area = form.get('area', '')
        job = form.get('job', '')
        if len(name) < 2:
            return render_template('user/setting.html', msg='用户名不能少于2位', user=u)
        elif User.find_by(username=name).id != u.id:
            return render_template('user/setting.html', msg='用户名已存在', user=u)
        else:
            if 'file' in request.files:
                file = request.files['file']
                # log('file', file)
                u.avatar = add_img(file)

            u.username = name
            if pwd is not '':
                u.password = User.salted_password(pwd)
            u.area = area
            u.job = job
            u.save()
            return render_template('user/setting.html', msg='修改成功', user=u)

def allow_img(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_img_type
    return suffix in accept_user_img_type

def add_img(file):
    if file.filename == '':
        return redirect(request.url)

    if allow_img(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_img_director, filename))
        return filename
    else:
        return ''

@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_img_director, filename)

@main.route("/people")
def people():
    user = current_user()
    if user is None:
        return redirect(url_for('user.login'))
    qu = Question.find_all(uid=user.id)
    an = Answer.find_all(uid=user.id)

    return render_template("user/people.html", user=user, qu=qu, an=an)

templates/user/login.html
{% extends "base.html" %}

{% block title %} 登陆 {% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container">

    <form  method="post" action="{{ url_for('user.login') }}">
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control input-xlarge" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        <div class="checkbox">
            <label>
                <p>{{ msg }}</p>
                <a href="{{ url_for('user.register') }}">没有账号?请注册</a>
            </label>
        </div>
        <button type="submit" class="btn btn-default">登录</button>
    </form>

</div>
{% endblock %}

templates/user/people.html
{% extends "base.html" %}

{% block title %} 我的主页 {% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}

<div class="container">
        <div class="row">
            <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ '/uploads/img/' + user.avatar }}" alt="" style="width: 30px; height: 30px;">
                        </div>
                        <div class="col-md-8">
                            <p>{{ user.username }}</p>
                            <p>地区：{{ user.area }} 职业：{{ user.job }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active"><a href="#question" data-toggle="tab" aria-expanded="true">我的问题</a></li>
                            <li role="presentation"><a href="#answer" data-toggle="tab" aria-expanded="true">我的答案</a></li>
                        </ul>
                    </div>


                    <div id="myTabContent" class="tab-content" style="padding: 10px;">
                        <div id="question"  class="tab-pane fade active in">
                            {% for vo in qu %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <p><a href="{{ url_for('question.detail', id=vo.id) }}">{{ vo.title }}</a></p>
                                        <p>{{ vo.content }}</p>
                                        <ul class="list-inline">
                                            <li><a href="{{ url_for('question.detail', id=vo.id) }}"><span class="glyphicon glyphicon-comment"></span> 回答问题 </a></li>
                                        </ul>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}
                        </div>

                        <div id="answer"  class="tab-pane fade">
                            {% for vo in an %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <p>回答了问题：<a href="{{ url_for('question.detail', id=vo.question().id) }}">{{ vo.question().title }}</a></p>
                                        <p>{{ vo.content }}</p>
                                        <ul class="list-inline">
                                            <li><a href="{{ url_for('question.detail', id=vo.question().id) }}"><span class="glyphicon glyphicon-comment"></span> 回答问题 </a></li>
                                        </ul>
                                    </div>
                                </div>
                                <hr>
                            {% endfor %}
                        </div>
                    </div>
                    

                    

            </div>
				
            <div class="col-md-4">
                <div class="row">

                </div>
            </div>
        </div>
</div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %} 注册 {% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" action="{{ url_for('user.register') }}">
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control input-xlarge" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        <div class="checkbox">
            <label>
                <p>{{ msg }}</p>
            </label>
        </div>
        <button type="submit" class="btn btn-default">注册</button>
    </form>
</div>
{% endblock %}

templates/user/setting.html
{% extends "base.html" %}

{% block title %} 设置 {% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block content %}

<div class="container">
    <form method="post" action="{{ url_for('user.setting') }}" enctype="multipart/form-data">
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control input-xlarge" id="username" name="username" value="{{ user.username }}">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password" value="" placeholder="空为不修改">
        </div>
        <div class="form-group">
            <label for="area">地区</label>
            <input type="text" class="form-control" id="area" name="area" value="{{ user.area }}">
        </div>
        <div class="form-group">
            <label for="job">职业</label>
            <input type="text" class="form-control" id="job" name="job" value="{{ user.job }}">
        </div>
        <div class="form-group">
            <label for="file">图片</label>
            <input type="file" id="file" name="file" >
            <p class="help-block">Example block-level help text here.</p>
        </div>
        <div class="checkbox">
            <label>
                <p>{{ msg }}</p>
            </label>
        </div>
        <button type="submit" class="btn btn-default">提交</button>
    </form>
</div>

{% endblock %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>设置</title>
</head>

<body>
    <h1>用户资料页面</h1>
    <form method=post action={{ url_for("user.setting") }} enctype=multipart/form-data> <div>
        <label>名称</label>
        <input type="text" name="username" value="{{ user.username }}">
        </div>
        <div>
            <label>密码</label>
            <input type="text" name="password" value="" placeholder="空为不修改">
        </div>
        <div>
            <label>地区</label>
            <input type="text" name="area" value=" {{ user.area }} ">
        </div>
        <div>
            <label>职业</label>
            <input type="text" name="job" value=" {{ user.job }} ">
        </div>
        <div>
            <label>图片</label>
            <input type=file name=file>
        </div>
        <input type=submit value=提交>
    </form>
    <p>{{ msg }}</p>

</body>

</html>